# Generated by Django 5.0 on 2023-12-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cliente_concordo_termos_cliente_promo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='concordo_termos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='promo_email',
            field=models.BooleanField(default=True),
        ),
    ]
