# Generated by Django 5.0 on 2024-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_alter_cliente_concordo_termos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='concordo_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='promo_email',
            field=models.BooleanField(default=False),
        ),
    ]
